### ISSUE TITLE
BovineMine 1.2 beta release doesn't have GO terms on NCBI genes, but does on Ensembl

### ISSUE THREAD

**Issue by cmdcolin** [elsiklab/bovinemine#12]
We uncovered this during some checks of the latest release

Compare RCAN1 on the bovinemine-release-1.2 vs the main site

**Comment by deepakunni3** [comment]
The root cause of this issue is that UniProt entries for RefSeq genes were not loaded even though the source for integration was run. 

GO-annotation integration relies on UniProt accessions.

**Comment by cmdcolin** [comment]
Looks fixed in latest iteration!
