### ISSUE TITLE
The ssid aliases show "no value" on SNP report page in 1.2

### ISSUE THREAD

**Issue by cmdcolin** [elsiklab/bovinemine#13]
![screenshot-bovinegenome org 2016-06-01 14-16-55](https://cloud.githubusercontent.com/assets/6511937/15722475/8a3cd672-2803-11e6-8927-023a8adb96cb.png)

Does show ssid on hover, no would be nice if that was shown in table

**Comment by cmdcolin** [comment]
still appears this way under aliases here http://bovinegenome.org/bovinemine-release-1.2/report.do?id=151867029&trail=|151867029

**Comment by deepakunni3** [comment]
Fixed via 10ae5d1
