### ISSUE TITLE
Indication of pseudogene on report page

### ISSUE THREAD

**Issue by cmdcolin** [elsiklab/bovinemine#3]
We have used ENSBTAG00000006858 as an example on our homepage which is marked as a pseudogene biotype in the ensembl track on jbrowse, but intermine doesn't mark it as such

http://bovinegenome.org/bovinemine/report.do?id=8000009&trail=|8000009

**Comment by deepakunni3** [comment]
As of commit a1b76482, this is now supported via biotype field for Gene entities.

**Comment by cmdcolin** [comment]
Awesome! thanks

**Comment by cmdcolin** [comment]
Might as well close, can reopen if something happens on final deploy. Would be good to start a changelog though too :)
